apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nfsdir-demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: webroot
          mountPath: /usr/share/nginx/html
        ports:
        - containerPort: 80
      volumes:
      - name: webroot
        nfs:
          server: 192.168.79.11
          path: /nfs