apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-demo-1
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  nfs:
    server: 192.168.79.11
    path: /nfs