apiVersion: v1
kind: Pod
metadata:
  name: pvc-pod-demo1
spec:
  containers:
    - name: pvc-pod-container
      image: busybox
      imagePullPolicy: IfNotPresent
      args:
      - /bin/sh
      - -c
      - sleep 30000
      volumeMounts:
      - mountPath: "/mydata"
        name: mydata
  volumes:
    - name: mydata
      persistentVolumeClaim:
        claimName: pvc-demo-1