apiVersion: v1
kind: Pod
metadata:
  name: first-pod
  labels:
    app: demo
    type: bash
spec:
  replicas: 2
  containers:
  - name: busybox-container
    image: busybox
    command: ['sh', '-c', 'echo Hello Kubernetes Pod! && sleep 1000']