apiVersion: v1
kind: Pod
metadata:
  name: resourcelimit-demo 
spec:
  containers:
  - name: db
    image: mysql
    imagePullPolicy: IfNotPresent
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "password"
    resources:
      requests:
        ## 设置请求的内存为64M
        memory: "64Mi"
        ## 设置请求的CPU资源为0.25核
        ## 数字1表示1核CPU，1.5表示1.5核CPU
        cpu: "250m" 
      limits:
        ## 设置请求的内存为128M
        memory: "128Mi"
        ## 设置请求的CPU资源为0.5核
        cpu: "500m" 
  - name: wp
    image: wordpress
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"