apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolling-update-demo
  labels:
    app: rolling-update-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rolling-update-demo
  template:
    metadata:
      labels:
        app: rolling-update-demo
        version: v2.0.0
    spec:
      containers:
      - name: rolling-update-demo
        image: collenzhao/k8s-deployment-strategies
        ports:
        - name: http
          containerPort: 8080
        env:
        - name: VERSION
          value: v2.0.0