apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mydemo-pod-reader-rolebinding
  namespace: mydemo
subjects:
- kind: User
  #名字大小写敏感
  name: Jerry
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role #this must be Role or ClusterRole
  # 名字必须与Role或者ClusterRole的名字一致
  name: mydemo-pod-reader-role 
  apiGroup: rbac.authorization.k8s.io